name: secret_key
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_screenutil: 5.0.0+2
  flutter_svg: 0.23.0+1
  google_fonts: 2.1.0
  contained_tab_bar_view: ^0.8.0
  flutter: 
    sdk: flutter
  random_string: ^2.3.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

